# Step 1: Use a specific Python base image
FROM pytorch/pytorch

# Step 2: Set the working directory
WORKDIR ___PROJECTS/EPIVERSE/search/


# Step 3: Copy the Python script into the container
COPY search_api_endpoint.py .
COPY requirements.txt .


    
    

#RUN pip install --default-timeout=900 --no-cache-dir -r requirements.txt
RUN pip install --default-timeout=900 -r requirements.txt


# Step 4: Command to run the Python script
#CMD ["python", "test.py"]
EXPOSE 8000
CMD ["uvicorn", "search_api_endpoint:app", "--host", "0.0.0.0", "--port", "8000"]