services:
  elasticsearch:
    image: elasticsearch:8.15.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  api:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile-poc-api
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch